name: Deploy API to GitHub

on:
  push:
    branches:
      - master  # ou master, dependendo de sua configuração

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'  # ou qualquer versão necessária para seu projeto

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: <nome-do-seu-app-no-azure>  # Nome do seu App no Azure
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Segredo configurado com o perfil de publicação do Azure
          package: ./publish
