name: Build, Test, and Deploy Docker Image

on:
  # Acionar o workflow para PRs abertos para qualquer branch
  pull_request:
    branches:
      - '*'  # Isso faz com que o workflow seja acionado para PRs em qualquer branch

  # Acionar o workflow para push na branch master
  push:
    branches:
      - master  # Isso faz com que o workflow seja acionado quando houver push na branch master

jobs:
  # Job para rodar os testes
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'  # Isso garante que essa parte só será executada em um PR

    steps:
      # Verificar o código do repositório
      - name: Check out repository
        uses: actions/checkout@v3

      # Configurar o .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Restaurar dependências do projeto
      - name: Restore dependencies
        run: dotnet restore "MinhaApi/MinhaApi.csproj"

      # Rodar os testes
      - name: Run tests
        run: dotnet test "MinhaApi.Tests/MinhaApi.Tests.csproj" --configuration Release

  # Job para construir e enviar a imagem Docker
  build_and_push:
    runs-on: ubuntu-latest
    needs: test  # Isso vai garantir que o job de testes passe antes do job de build e push
    if: github.event_name == 'push'  # Isso garante que essa parte só será executada em um push para a branch master

    steps:
      # Verificar o código do repositório
      - name: Check out repository
        uses: actions/checkout@v3

      # Logar no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }} 

      # Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -t eduardovbt/minhaapi:${{ github.sha }} -f ./MinhaApi/Dockerfile .
          docker tag eduardovbt/minhaapi:${{ github.sha }} eduardovbt/minhaapi:latest

      # Enviar a imagem para o Docker Hub
      - name: Push Docker image
        run: |
          docker push eduardovbt/minhaapi:${{ github.sha }}
          docker push eduardovbt/minhaapi:latest
