name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - master   # Dispara quando um PR for aceito para a branch master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./MinhaApi/Dockerfile
        push: true
        tags: minha-api:${{ github.sha }}
	platform: linux/amd64  # Especifica a plataforma correta

    - name: Logout from Docker Hub
      run: docker logout
