name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master  # Pode ser qualquer branch em que você queira que o GitHub Actions dispare
  pull_request:
    branches:
      - master  # Também para pull requests para a branch master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Defina seu nome de usuário Docker no GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}   # Defina sua senha Docker no GitHub Secrets

      - name: Build Docker image
        run: |
          docker build --build-arg BUILD_CONFIGURATION=Release -t minha-api:${{ github.sha }} .
      
      - name: Push Docker image
        run: |
          docker push minha-api:${{ github.sha }}

