name: Build and Push Docker Image

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Verificar o código do repositório
      - name: Check out repository
        uses: actions/checkout@v3

      # Logar no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }} 

      # Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -t eduardovbt/minhaapi:${{ github.sha }} -f ./MinhaApi/Dockerfile .
          docker tag eduardovbt/minhaapi:${{ github.sha }} eduardovbt/minhaapi:latest

      # Enviar a imagem para o Docker Hub
      - name: Push Docker image
        run: |
          docker push eduardovbt/minhaapi:${{ github.sha }}
          docker push eduardovbt/minhaapi:latest
