name: Build, Test, and Deploy Docker Image

on:
  pull_request:
    branches:
      - '*'  # Isso faz com que o workflow seja acionado para PRs em qualquer branch

  push:
    branches:
      - main  # A execução do build e push só acontecerá quando houver push para a branch principal

jobs:
  
  # Job para rodar os testes
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'  # Isso garante que essa parte só será executada em um PR

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore "MinhaApi/MinhaApi.csproj"

      - name: Run tests
        run: dotnet test "MinhaApi.Tests/MinhaApi.Tests.csproj" --configuration Release
