name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - master  # Dispara quando um PR for aceito para a branch master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./MinhaApi  # Define o contexto da construção da imagem
        file: ./MinhaApi/Dockerfile  # Caminho para o Dockerfile dentro do diretório 'MinhaApi'
        push: true  # Habilita o envio da imagem para o Docker Hub
        tags: minha-api:${{ github.sha }}  # Usa o sha do commit como tag da imagem

    - name: Logout from Docker Hub
      run: docker logout
